import {quizAPI as api} from './quiz-api.js';
const letters=['A','B','C','D'];
const badges=['🏆 Quiz Champion','⚡ Fastest Finger','🔥 5 Correct Answers in a Row','🎯 Perfect Score','🧠 Knowledge Master','⭐ Top Performer','🚀 Quick Thinker'];
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
function table(headers,rows){const wrap=el('div',undefined,'quiz-table-wrap'),t=el('table'),head=el('thead'),tr=el('tr');headers.forEach(x=>tr.append(el('th',x)));head.append(tr);t.append(head);const body=el('tbody');rows.forEach(row=>{const r=el('tr');row.forEach(x=>r.append(el('td',String(x))));body.append(r);});t.append(body);wrap.append(t);return wrap;}
export class LiveQuiz {
 constructor({code,sessionId,uid,teacher,report}){
  Object.assign(this,{code,sessionId,uid,teacher,report});this.off=[];this.state=null;this.answer=null;this.offset=0;this.clockReady=false;this.answerOff=null;
  this.panel=document.getElementById('quizPanel');this.stage=document.getElementById('quizStage');this.controls=document.getElementById('quizControls');this.result=document.getElementById('publicLeaderboard');this.base=`liveClassrooms/${code}/sessions/${sessionId}`;
  this.off.push(api.watch(`${this.base}/state/quiz`,q=>this.receive(q),report),api.watch(`${this.base}/state/leaderboard`,s=>this.leaderboard(s),report),api.watch(`${this.base}/state/badges`,s=>this.publicBadges(s),report));
  if(teacher)this.buildControls();else this.controls.hidden=true;
  this.syncClock();this.clockTimer=setInterval(()=>this.syncClock(),30000);this.timer=setInterval(()=>this.tick(),100);
 }
 async syncClock(){try{const start=Date.now(),s=await api.call('quizClock',{});this.offset=s.now-(start+Date.now())/2;this.clockReady=true;this.tick();}catch(e){this.report(e);}}
 call(action,extra={}){return api.call('quizAction',{code:this.code,sessionId:this.sessionId,action,expectedRoundId:this.state?.roundId||null,...extra});}
 button(text,action,extra={}){const b=el('button',text);b.type='button';b.onclick=async()=>{b.disabled=true;try{await this.call(action,typeof extra==='function'?extra():extra);}catch(e){this.report(e);}finally{b.disabled=false;}};return b;}
 buildControls(){
  this.controls.hidden=false;const title=el('h3','Teacher quiz studio'),select=el('select');select.id='savedQuiz';select.setAttribute('aria-label','Saved quiz');this.controls.append(title,select,this.button('Start quiz','start',()=>({quizId:select.value})));
  this.off.push(api.list(`users/${this.uid}/quizzes`,rows=>{const chosen=select.value||new URLSearchParams(location.search).get('quiz');select.replaceChildren(el('option','Select a saved quiz'));select.firstChild.value='';for(const row of rows){const o=el('option',row.title);o.value=row.id;select.append(o);}if([...select.options].some(o=>o.value===chosen))select.value=chosen;},this.report));
  const grid=el('div',undefined,'quiz-control-grid');for(const [label,action,extra] of [['Pause','pause'],['Resume','resume'],['Previous','previous'],['Next','next'],['Skip','skip'],['End quiz','end'],['Show correct answer','reveal'],['Show Fastest Finger','fastest',{visible:true}],['Hide Fastest Finger','fastest',{visible:false}],['Show leaderboard','leaderboard',{visible:true}],['Hide leaderboard','leaderboard',{visible:false}],['Show badges','badges',{visible:true}],['Hide badges','badges',{visible:false}]])grid.append(this.button(label,action,extra||{}));this.controls.append(grid);
  const award=el('div',undefined,'award-controls');this.studentSelect=el('select');this.studentSelect.setAttribute('aria-label','Student for award');const points=el('input');points.type='number';points.min=1;points.max=1000;points.value=25;points.setAttribute('aria-label','Bonus points');const badge=el('select');badge.setAttribute('aria-label','Achievement badge');badges.forEach(x=>{const o=el('option',x);o.value=x;badge.append(o);});award.append(this.studentSelect,points,this.button('Give bonus points','bonus',()=>({studentUid:this.studentSelect.value,points:+points.value,actionId:crypto.randomUUID()})),badge,this.button('Award badge','badge',()=>({studentUid:this.studentSelect.value,badge:badge.value,actionId:crypto.randomUUID()})));this.controls.append(award);
 }
 setPeople(rows){if(!this.studentSelect)return;const value=this.studentSelect.value;this.studentSelect.replaceChildren();const seen=new Set();for(const p of rows){if(p.role!=='student'||seen.has(p.uid))continue;seen.add(p.uid);const o=el('option',p.name);o.value=p.uid;this.studentSelect.append(o);}if(seen.has(value))this.studentSelect.value=value;}
 receive(q){const prior=this.state?.roundId;this.state=q;if(q?.roundId!==prior){this.answer=null;this.answerOff?.();if(q&&!this.teacher)this.answerOff=api.watch(`${this.base}/quizRounds/${q.roundId}/answers/${this.uid}`,a=>{if(this.state?.roundId!==q.roundId)return;this.answer=a;this.render();},this.report);}this.render();}
 render(){
  const q=this.state;this.panel.replaceChildren();this.stage.replaceChildren();this.stage.hidden=!q||(q.status==='ended'&&!q.showFastest&&!q.showCorrect);
  if(!q){this.panel.append(el('p','Your teacher will start the next quiz here.','quiz-idle'));return;}
  const label=el('div',`${q.title} · ${q.index+1} / ${q.total}`,'quiz-kicker');this.panel.append(label);this.panel.append(el('h3',q.question));
  this.panelTimer=el('strong','—','quiz-timer');this.panel.append(this.panelTimer);
  const options=el('div',undefined,'answer-grid');q.options.forEach((text,i)=>{const b=el('button',undefined,'answer option-'+i);b.append(el('span',letters[i],'answer-letter'),el('span',text));b.setAttribute('aria-pressed',String(this.answer?.choice===i));b.onclick=()=>this.submit(i);options.append(b);});this.panel.append(options);this.answerButtons=[...options.children];this.answerStatus=el('p',this.answer?'Answer saved'+(q.allowChange?' · You may change it before time runs out.': ' · Locked.'):'Choose one answer.','answer-status');this.panel.append(this.answerStatus);
  this.stage.append(el('div','VOCALCLASS LIVE QUIZ','quiz-kicker'));const top=el('div',undefined,'quiz-stage-title');this.stageTimer=el('strong','—','quiz-timer');top.append(el('h2',q.question),this.stageTimer);this.stage.append(top);
  const mirror=el('div',undefined,'answer-grid mirror');q.options.forEach((text,i)=>{const row=el('div',undefined,'answer option-'+i);row.append(el('span',letters[i],'answer-letter'),el('span',text));mirror.append(row);});this.stage.append(mirror);
  if(q.showCorrect){const reveal=el('div',undefined,'quiz-explanation');reveal.append(el('strong',`Correct answer: ${letters[q.correct]}. ${q.options[q.correct]}`),el('p',q.explanation));this.stage.append(reveal);this.panel.append(el('p',`Correct: ${letters[q.correct]}. ${q.options[q.correct]}`));}
  if(q.showFastest){this.stage.append(el('h3','⚡ Fastest Finger · Top 10'));if(q.fastest?.length)this.stage.append(table(['Rank','Student','Answer','Response time','Points'],q.fastest.slice(0,10).map(r=>[r.rank,r.name,letters[r.choice],(r.responseMs/1000).toFixed(2)+' sec','+'+r.points])));else this.stage.append(el('p','No correct answers this round.'));}
  this.tick();
 }
 tick(){const q=this.state;if(!q)return;const left=q.status==='paused'?q.remainingMs:q.status==='running'?Math.max(0,q.endsAt-(Date.now()+this.offset)):0;const seconds=Math.ceil(left/1000),text=q.status==='paused'?'Paused · '+seconds+'s':String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');for(const t of [this.panelTimer,this.stageTimer])if(t){t.textContent=text;t.classList.toggle('urgent',left>0&&left<=10000&&q.status==='running');}for(const b of this.answerButtons||[])b.disabled=this.teacher||!this.clockReady||this.sending||q.status!=='running'||left<=0||!!this.answer&&!q.allowChange;if(q.status==='running'&&left<=0)this.answerStatus.textContent='Time’s up. Answers are locked.';}
 async submit(choice){if(this.sending)return;this.sending=true;const roundId=this.state.roundId;this.tick();try{const result=await api.call('submitQuizAnswer',{code:this.code,sessionId:this.sessionId,roundId,choice});if(this.state?.roundId===roundId){this.answer=result;this.render();}}catch(e){this.report(e);}finally{this.sending=false;this.tick();}}
 leaderboard(s){this.result.replaceChildren();this.result.hidden=!s?.visible;if(!s?.visible)return;this.result.append(el('h2','🏆 Class leaderboard'));this.result.append(table(['Rank','Student','Correct answers','Quiz played','Points'],(s.rows||[]).map((r,i)=>[i+1,r.name,r.correct,r.played,r.points])));}
 publicBadges(s){const area=document.getElementById('publicBadges');area.replaceChildren();area.hidden=!s?.visible;if(s?.visible){area.append(el('h3','Class achievements'));for(const r of s.rows||[])area.append(el('p',r.name+' · '+r.badge));}}
 destroy(){this.off.forEach(f=>f());this.answerOff?.();clearInterval(this.timer);clearInterval(this.clockTimer);this.controls.replaceChildren();this.panel.replaceChildren();this.stage.replaceChildren();}
}
