import {quizAPI as api} from './quiz-api.js';
const letters=['A','B','C','D'];
const blank=()=>({question:'',options:['','','',''],correct:0,duration:30,points:100,explanation:'',allowChange:false});
export class QuizLibrary{
 constructor(host,uid,report){this.host=host;this.uid=uid;this.report=report;this.id=null;this.questions=[blank()];this.index=0;this.off=null;this.alive=true;this.build();}
 build(){
  this.host.innerHTML=`<div class="page-intro"><p class="eyebrow">PREPARE. LAUNCH. INSPIRE.</p><h2>Your quiz studio</h2><p>Prepare up to 30 questions. Launch a saved quiz from the live classroom.</p></div><div class="quiz-library"><aside class="panel quiz-saved"><h3>Saved quizzes</h3><div id="quizSavedList"></div><button id="quizNew">＋ New quiz</button></aside><div class="panel quiz-editor"><label>Quiz title<input id="quizTitle" maxlength="100" required></label><div id="questionOrder" class="question-order"></div><form id="quizEditForm"><label>Question<textarea id="editQuestion" maxlength="500" required></textarea></label><div class="quiz-option-fields">${letters.map((x,i)=>`<label>Option ${x}<input id="editOption${i}" maxlength="160" required></label>`).join('')}</div><div class="quiz-settings"><label>Correct answer<select id="editCorrect">${letters.map((x,i)=>`<option value="${i}">${x}</option>`).join('')}</select></label><label>Timer (1–60 seconds)<input id="editDuration" type="number" min="1" max="60" value="30" required></label><label>Points<input id="editPoints" type="number" min="1" max="1000" value="100" required></label></div><div id="quickTimers" class="quick-timers"></div><label>Explanation<textarea id="editExplanation" maxlength="1500"></textarea></label><label class="quiz-checkbox"><input id="editAllowChange" type="checkbox"> Allow answer changes before time runs out</label><div class="quiz-editor-actions"><button type="button" id="quizAdd">Add question</button><button type="button" id="quizDuplicate">Duplicate</button><button type="button" id="quizDeleteQuestion">Delete question</button><button type="button" id="quizUp">Move up</button><button type="button" id="quizDown">Move down</button><button class="primary" id="quizSave">Save quiz</button></div></form><div class="quiz-launch"><label>Class code<input id="quizClassCode" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="123456"></label><button id="quizLaunch">Open classroom to start quiz ↗</button></div><p id="quizSaveStatus" role="status">Unsaved quiz</p></div></div>`;
  this.$=id=>this.host.querySelector('#'+id);this.$('quizNew').onclick=()=>{if(!confirm('Start a new quiz? Unsaved edits will be discarded.'))return;this.id=null;this.questions=[blank()];this.index=0;this.$('quizTitle').value='';this.load();};
  for(const seconds of [5,10,15,20,30,45,60]){const b=document.createElement('button');b.type='button';b.textContent=seconds+'s';b.onclick=()=>this.$('editDuration').value=seconds;this.$('quickTimers').append(b);}
  this.$('quizAdd').onclick=()=>{if(this.questions.length>=30)return this.report(Error('Maximum 30 questions per quiz.'));this.capture();this.questions.push(blank());this.index=this.questions.length-1;this.load();};
  this.$('quizDuplicate').onclick=()=>{if(this.questions.length>=30)return;this.capture();this.questions.splice(this.index+1,0,structuredClone(this.questions[this.index]));this.index++;this.load();};
  this.$('quizDeleteQuestion').onclick=()=>{if(!confirm('Delete this question?'))return;this.questions.splice(this.index,1);if(!this.questions.length)this.questions=[blank()];this.index=Math.min(this.index,this.questions.length-1);this.load();};
  for(const [id,dir] of [['quizUp',-1],['quizDown',1]])this.$(id).onclick=()=>{this.capture();const next=this.index+dir;if(next<0||next>=this.questions.length)return;[this.questions[next],this.questions[this.index]]=[this.questions[this.index],this.questions[next]];this.index=next;this.load();};
  this.$('quizEditForm').onsubmit=async e=>{e.preventDefault();this.capture();const button=this.$('quizSave');button.disabled=true;try{const result=await api.call('saveQuiz',{id:this.id,quiz:{title:this.$('quizTitle').value,questions:this.questions}});if(!this.alive)return;this.id=result.id;this.$('quizSaveStatus').textContent='Saved. Ready to launch in class.';}catch(e){this.report(e);}finally{button.disabled=false;}};
  this.$('quizLaunch').onclick=()=>{const code=this.$('quizClassCode').value.trim();if(!this.id)return this.report(Error('Save your quiz first.'));if(!/^\d{6}$/.test(code))return this.report(Error('Enter your six-digit class code.'));location.href='classroom-room.html?role=teacher&code='+code+'&quiz='+encodeURIComponent(this.id);};
  this.off=api.list(`users/${this.uid}/quizzes`,rows=>{if(!this.alive)return;this.$('quizSavedList').replaceChildren();for(const row of rows){const item=document.createElement('div'),open=document.createElement('button'),del=document.createElement('button');open.textContent=row.title+' · '+row.questions.length+' questions';open.onclick=()=>{if(!confirm('Open this quiz? Unsaved edits will be discarded.'))return;this.id=row.id;this.questions=structuredClone(row.questions);this.index=0;this.$('quizTitle').value=row.title;this.load();};del.textContent='Delete';del.onclick=async()=>{if(confirm('Delete saved quiz “'+row.title+'”?'))try{await api.removeQuiz(this.uid,row.id);}catch(e){this.report(e);}};item.append(open,del);this.$('quizSavedList').append(item);}},this.report);this.load();
 }
 capture(){this.questions[this.index]={question:this.$('editQuestion').value,options:letters.map((_,i)=>this.$('editOption'+i).value),correct:+this.$('editCorrect').value,duration:+this.$('editDuration').value,points:+this.$('editPoints').value,explanation:this.$('editExplanation').value,allowChange:this.$('editAllowChange').checked};}
 load(){const q=this.questions[this.index];this.$('editQuestion').value=q.question;q.options.forEach((x,i)=>this.$('editOption'+i).value=x);this.$('editCorrect').value=q.correct;this.$('editDuration').value=q.duration;this.$('editPoints').value=q.points;this.$('editExplanation').value=q.explanation;this.$('editAllowChange').checked=q.allowChange;this.$('questionOrder').replaceChildren();this.questions.forEach((q,i)=>{const b=document.createElement('button');b.textContent='Q'+(i+1);b.setAttribute('aria-pressed',String(i===this.index));b.onclick=()=>{this.capture();this.index=i;this.load();};this.$('questionOrder').append(b);});this.$('quizUp').disabled=this.index===0;this.$('quizDown').disabled=this.index===this.questions.length-1;}
 destroy(){this.alive=false;this.off?.();this.host.replaceChildren();}
}
