const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),server=require('./server.cjs');
function samplePDF(){const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 340] /Resources << /Font << /F1 5 0 R >> >> /Contents 6 0 R >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 340] /Resources << /Font << /F1 5 0 R >> >> /Contents 7 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];for(const text of ['Lesson page ONE','Lesson page TWO']){const stream=`BT /F1 32 Tf 50 180 Td (${text}) Tj ET`;objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);}let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const start=Buffer.byteLength(pdf);pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(const offset of offsets.slice(1))pdf+=String(offset).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return Buffer.from(pdf);}
const stored=new Map();let state=null,browser;const errors=[];
(async()=>{await new Promise(r=>server.listen(4181,'127.0.0.1',r));browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,headless:true});try{
 const context=await browser.newContext({viewport:{width:1280,height:1000}});
 await context.route('**/classroom-app.js',r=>r.fulfill({contentType:'text/javascript',body:''}));await context.route('**/firebase-config.js',r=>r.fulfill({contentType:'text/javascript',body:'export const auth={app:{},currentUser:{getIdToken:async()=>"test"}};'}));
 await context.route('https://www.gstatic.com/firebasejs/**/firebase-storage.js',r=>r.fulfill({contentType:'text/javascript',body:'export const getStorage=()=>({}),ref=(s,p)=>p,uploadBytes=async(p,b)=>window.files("write",p,Array.from(b)),getBytes=async p=>new Uint8Array(await window.files("read",p)).buffer;'}));
 await context.route('**/quiz-api.js',r=>r.fulfill({contentType:'text/javascript',body:'export const quizAPI={call:async(name,d)=>window.lessonState(d.patch)};'}));
 await context.exposeBinding('files',(_,op,p,bytes)=>{if(op==='write'){stored.set(p,bytes);return;}return stored.get(p);});await context.exposeBinding('lessonState',(_,patch)=>{if(patch)state={...state,...patch};return state;});
 async function open(teacher){const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4181/classroom-room.html');await p.evaluate(async teacher=>{document.querySelector('#lobby').hidden=true;document.querySelector('#classroom').hidden=false;const {LessonPresentation}=await import('./classroom-presentation.js');const store={watch:(path,next)=>{let last;const t=setInterval(async()=>{const s=await window.lessonState();if(JSON.stringify(s)!==last){last=JSON.stringify(s);next(s);}},100);return()=>clearInterval(t);}};window.presentation=new LessonPresentation({code:'123456',sessionId:'lesson',teacher,store,report:e=>{window.presentationError=e.message;}});},teacher);return p;}
 const teacher=await open(true),student=await open(false);await teacher.locator('#uploadPDF').setInputFiles({name:'lesson.pdf',mimeType:'application/pdf',buffer:samplePDF()});
 await teacher.waitForFunction(()=>document.querySelector('#lessonPage').width>300||window.presentationError,{},{timeout:45000});const error=await teacher.evaluate(()=>window.presentationError);if(error)throw Error(error);
 assert.equal(await teacher.evaluate(()=>presentation.state.pages),2);assert.equal(await teacher.evaluate(()=>presentation.state.page),1);assert(await student.locator('#presentationPane').isHidden());assert.equal(stored.size,0);assert(await student.locator('#presentationControls').isHidden());const first=await teacher.locator('#lessonPage').evaluate(c=>c.toDataURL());
 await teacher.locator('#nextPage').click();await teacher.waitForFunction(()=>document.querySelector('#presentationStatus').textContent.includes('2 / 2'));const second=await teacher.locator('#lessonPage').evaluate(c=>c.toDataURL());assert.notEqual(first,second);
 await teacher.locator('#zoomIn').click();assert.equal(await teacher.evaluate(()=>presentation.state.zoom),1.25);await teacher.locator('#fitPresentation').click();assert.equal(await teacher.evaluate(()=>presentation.state.zoom),1);await teacher.locator('#closePresentation').click();await teacher.locator('#presentationPane').waitFor({state:'hidden'});assert.deepEqual(errors,[]);console.log('PASS local PDF rendering, two-page navigation, zoom/fit, close, student controls hidden; no Storage upload or shared document record.');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1);});
