const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),server=require('./server.cjs');
const mock=`const listeners=new Map();window.calls=[];window.records={};window.setRecord=(path,value)=>{window.records[path]=value;for(const f of listeners.get(path)||[])f(value);};export const quizAPI={call:async(name,data)=>{window.calls.push({name,data});if(name==='quizClock')return {now:Date.now()};if(name==='submitQuizAnswer')return {choice:data.choice,responseMs:1234};return {id:'saved-quiz'};},watch:(path,next)=>{if(!listeners.has(path))listeners.set(path,new Set());listeners.get(path).add(next);queueMicrotask(()=>next(window.records[path]||null));return()=>listeners.get(path).delete(next);},list:(path,next)=>{queueMicrotask(()=>next([]));return()=>{};},removeQuiz:async()=>{}};`;
let browser;const timeout=setTimeout(()=>{console.error('Quiz UI test exceeded 120 seconds.');browser?.close().finally(()=>process.exit(1));},120000);
(async()=>{console.log('Starting quiz UI checks');await new Promise(r=>server.listen(4180,'127.0.0.1',r));browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||undefined,headless:true});console.log('Browser ready');try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/classroom-app.js',r=>r.fulfill({contentType:'text/javascript',body:''}));await context.route('**/dashboard.js',r=>r.fulfill({contentType:'text/javascript',body:''}));await context.route('**/quiz-api.js',r=>r.fulfill({contentType:'text/javascript',body:mock}));
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:4180/classroom-room.html');
 await page.evaluate(async()=>{document.querySelector('#lobby').hidden=true;document.querySelector('#classroom').hidden=false;document.querySelector('#className').textContent='The solar system · Science';document.querySelector('#roomStatus').textContent='Connected · Student';document.querySelector('#classCode').textContent='123456';const {LiveQuiz}=await import('./classroom-quiz.js');window.quiz=new LiveQuiz({code:'123456',sessionId:'lesson',uid:'student',teacher:false,report:e=>{throw e;}});const teacher=document.createElement('article');teacher.className='video-tile teacher';teacher.innerHTML='<div class="demo-teacher">AV<span>Teacher camera · preview</span></div>';document.querySelector('#teacherVideoDock').append(teacher);const style=document.createElement('style');style.textContent='.demo-teacher{height:100%;display:grid;place-content:center;text-align:center;font-size:48px;color:#ded6ff;background:radial-gradient(circle at 30% 0,#5c578d,#1a2945)}.demo-teacher span{font-size:12px;color:#b8c5df}';document.head.append(style);window.setRecord('liveClassrooms/123456/sessions/lesson/state/quiz',{roundId:'round',index:0,total:5,title:'Discover our solar system',question:'Which planet is known as the Red Planet?',options:['Earth','Mars','Venus','Jupiter'],status:'running',startedAt:Date.now(),endsAt:Date.now()+60000,duration:60,allowChange:false,fastest:[]});});
 await page.waitForFunction(()=>document.querySelector('#quizPanel .answer')?.disabled===false);assert.equal(await page.locator('#quizPanel .answer').count(),4);assert.equal(await page.locator('#quizControls').isHidden(),true);assert((await page.locator('#quizStage').innerText()).includes('Red Planet'));assert.match(await page.locator('#quizPanel .quiz-timer').innerText(),/^(01:00|00:59)$/);
 const letters=await page.locator('#quizPanel .answer-letter').allTextContents();assert.deepEqual(letters,['A','B','C','D']);await page.locator('#quizPanel .answer').nth(1).click();await page.waitForFunction(()=>document.querySelector('#quizPanel .answer').disabled);assert.equal(await page.locator('#quizPanel .answer').nth(1).getAttribute('aria-pressed'),'true');
 await page.evaluate(()=>window.setRecord('liveClassrooms/123456/sessions/lesson/state/quiz',{...window.quiz.state,allowChange:true,endsAt:Date.now()+9000}));assert(await page.locator('#quizPanel .quiz-timer').evaluate(e=>e.classList.contains('urgent')));await page.locator('#quizPanel .answer').nth(2).click();assert.equal(await page.locator('#quizPanel .answer').nth(2).getAttribute('aria-pressed'),'true');
 await page.evaluate(()=>window.setRecord('liveClassrooms/123456/sessions/lesson/state/quiz',{...window.quiz.state,endsAt:Date.now()-1000}));assert(await page.locator('#quizPanel .answer').first().isDisabled());assert.equal(await page.locator('#quizPanel .quiz-timer').innerText(),'00:00');
 await page.evaluate(()=>window.setRecord('liveClassrooms/123456/sessions/lesson/state/quiz',{...window.quiz.state,status:'paused',remainingMs:20000}));assert((await page.locator('#quizPanel .quiz-timer').innerText()).includes('Paused'));assert(await page.locator('#quizPanel .answer').first().isDisabled());
 await page.evaluate(()=>window.setRecord('liveClassrooms/123456/sessions/lesson/state/quiz',{...window.quiz.state,status:'running',endsAt:Date.now()+45000}));
 const artifacts=path.join(__dirname,'artifacts');fs.mkdirSync(artifacts,{recursive:true});await page.screenshot({path:path.join(artifacts,'quiz-student.png'),fullPage:true,animations:'disabled'});
 await page.evaluate(()=>{window.setRecord('liveClassrooms/123456/sessions/lesson/state/quiz',{...window.quiz.state,status:'finished',showFastest:true,fastest:Array.from({length:12},(_,i)=>({rank:i+1,name:'Student '+(i+1),choice:1,responseMs:1210+i*300,points:100-i*5}))});window.setRecord('liveClassrooms/123456/sessions/lesson/state/leaderboard',{visible:true,rows:[{name:'Maya',correct:8,played:10,points:850}]});});assert.equal(await page.locator('#quizStage tbody tr').count(),10);assert(await page.locator('#publicLeaderboard').isVisible());await page.evaluate(()=>window.setRecord('liveClassrooms/123456/sessions/lesson/state/leaderboard',{visible:false,rows:[]}));assert(await page.locator('#publicLeaderboard').isHidden());
 for(const width of [768,390,320]){await page.setViewportSize({width,height:950});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width);}await page.screenshot({path:path.join(artifacts,'quiz-student-mobile.png'),fullPage:true,animations:'disabled'});
 await page.goto('http://127.0.0.1:4180/teacher.html');await page.evaluate(async()=>{document.querySelector('#loading').hidden=true;document.querySelector('#app').hidden=false;document.querySelector('#pageTitle').textContent='Create quiz';document.querySelectorAll('nav [data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab==='quizzes'?'page':'false'));document.querySelectorAll('[data-section]').forEach(s=>s.hidden=s.dataset.section!=='quizzes');const {QuizLibrary}=await import('./quiz-library.js');window.library=new QuizLibrary(document.querySelector('#quizLibrary'),'teacher',e=>{throw e;});});await page.setViewportSize({width:1440,height:1000});await page.locator('#quizTitle').fill('Discover our solar system');await page.locator('#editQuestion').fill('Which planet is known as the Red Planet?');for(const [i,x] of ['Earth','Mars','Venus','Jupiter'].entries())await page.locator('#editOption'+i).fill(x);await page.locator('#editCorrect').selectOption('1');await page.locator('#editExplanation').fill('Iron minerals give Mars its reddish colour.');await page.locator('#quizDuplicate').click();assert.equal(await page.locator('#questionOrder button').count(),2);await page.locator('#quizUp').click();assert.equal(await page.locator('#questionOrder button').first().getAttribute('aria-pressed'),'true');await page.locator('#quizSave').click();await page.waitForFunction(()=>document.querySelector('#quizSaveStatus').textContent.startsWith('Saved'));assert.equal(await page.evaluate(()=>window.calls.find(x=>x.name==='saveQuiz').data.quiz.questions.length),2);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(artifacts,'quiz-studio.png'),fullPage:true,animations:'disabled'});
 assert.deepEqual(errors,[]);console.log('PASS real quiz/editor UI: A–D, timer formatting, urgency, pause/expiry lock, answer changes, Top 10, hidden student controls, teacher-published rankings, duplicate/reorder/save and mobile widths.');
 }finally{clearTimeout(timeout);await browser.close();server.close();}})().catch(e=>{console.error(e);clearTimeout(timeout);process.exit(1);});
