const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
let now=100000;const records=new Map(),enqueued=[];let queue=Promise.resolve();
const snap=p=>({id:p.split('/').pop(),exists:records.has(p),data:()=>records.get(p)});
const doc=p=>({path:p,get:async()=>snap(p),set:async(d,o)=>{records.set(p,o?.merge?{...records.get(p),...d}:d);},update:async d=>{if(!records.has(p))throw Error('Missing document');records.set(p,{...records.get(p),...d});}});
const collection=(p,filters=[])=>({where:(key,op,value)=>collection(p,[...filters,{key,value}]),get:async()=>{const docs=[...records.keys()].filter(k=>k.startsWith(p+'/')&&k.split('/').length===p.split('/').length+1&&filters.every(f=>records.get(k)[f.key]===f.value)).map(snap);return {docs,empty:!docs.length};}});
const db={doc,collection,runTransaction:fn=>{const run=queue.then(()=>fn({get:ref=>ref.get(),set:(ref,d,o)=>ref.set(d,o),update:(ref,d)=>ref.update(d)}));queue=run.catch(()=>{});return run;},batch:()=>{const operations=[];return {set:(ref,d,o)=>operations.push(()=>ref.set(d,o)),commit:async()=>{for(const op of operations)await op();}};}};
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
const exported={};class Clock extends Date{static now(){return now;}}
const sandbox={exports:exported,Buffer,Date:Clock,console,require:id=>{if(id==='firebase-admin/app')return {initializeApp(){}};if(id==='firebase-admin/firestore')return {getFirestore:()=>db};if(id==='firebase-admin/functions')return {getFunctions:()=>({taskQueue:()=>({enqueue:async(...args)=>enqueued.push(args)})})};if(id==='firebase-functions/v2/https')return {HttpsError,onCall:(options,fn)=>fn};if(id==='firebase-functions/v2/tasks')return {onTaskDispatched:(options,fn)=>fn};if(id==='firebase-functions/v2/firestore')return {onDocumentWritten:(options,fn)=>fn};if(id==='./quiz-core.cjs')return require('../functions/quiz-core.cjs');return require(id);}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../functions/index.js'),'utf8'),sandbox);
const base='liveClassrooms/123456/sessions/lesson',root='liveClassrooms/123456';
records.set('activationCodes/123456',{active:true,teacherId:'teacher'});records.set(root,{active:true,sessionId:'lesson'});records.set(base,{teacherUid:'teacher'});
for(const uid of ['s1','s2']){records.set(`${base}/participants/${uid}`,{uid,role:'student',online:true,lastSeen:{toMillis:()=>now}});records.set(`users/${uid}/profiles/student`,{displayName:uid==='s1'?'Samarth':'Rahul'});}
const invoke=(name,uid,data)=>exported[name]({auth:uid?{uid,token:{firebase:{sign_in_provider:'password'}}}:null,data:{code:'123456',sessionId:'lesson',...data}});
const question={question:'Choose B',options:['A option','B option','C option','D option'],correct:1,duration:5,points:100,explanation:'Because B is right.',allowChange:false};
(async()=>{
 await assert.rejects(()=>invoke('saveQuiz',null,{quiz:{title:'x',questions:[question]}}),/Sign in/);
 const bank=await invoke('saveQuiz','teacher',{quiz:{title:'Lesson quiz',questions:[question,{...question,allowChange:true}]}});
 await assert.rejects(()=>invoke('quizAction','s1',{action:'start',quizId:bank.id}),/Only the teacher/);
 await invoke('quizAction','teacher',{action:'start',quizId:bank.id});let q=records.get(`${base}/state/quiz`);assert.equal(q.options.length,4);assert.equal(q.correct,undefined);assert.equal(q.explanation,undefined);
 await exported.queueQuestion({params:{code:'123456',sessionId:'lesson'},data:{after:{data:()=>q}}});assert.equal(enqueued.length,1);
 now+=1210;await invoke('submitQuizAnswer','s1',{roundId:q.roundId,choice:1});await assert.rejects(()=>invoke('submitQuizAnswer','s1',{roundId:q.roundId,choice:0}),/already locked/);
 now+=420;await invoke('submitQuizAnswer','s2',{roundId:q.roundId,choice:1});await invoke('quizAction','teacher',{action:'pause'});await assert.rejects(()=>invoke('submitQuizAnswer','s2',{roundId:q.roundId,choice:2}),/closed/);now+=50000;await exported.expireQuestion({data:{code:'123456',sessionId:'lesson',roundId:q.roundId,revision:q.revision}});assert.equal(records.get(`${base}/state/quiz`).status,'paused');await invoke('quizAction','teacher',{action:'resume'});q=records.get(`${base}/state/quiz`);now=q.endsAt;await assert.rejects(()=>invoke('submitQuizAnswer','s2',{roundId:q.roundId,choice:2}),/closed/);
 const task={data:{code:'123456',sessionId:'lesson',roundId:q.roundId,revision:q.revision}};await exported.expireQuestion(task);await exported.expireQuestion(task);q=records.get(`${base}/state/quiz`);assert.equal(q.status,'finished');assert.equal(q.fastest[0].name,'Samarth');assert.equal(q.fastest[0].responseMs,1210);assert.equal(records.get(`${root}/quizScores/s1`).points,105);assert.equal(records.get(`${root}/quizScores/s2`).points,100);
 assert.equal(records.get(`${base}/state/leaderboard`),undefined);await assert.rejects(()=>invoke('quizAction','s1',{action:'leaderboard',visible:true}),/Only the teacher/);await invoke('quizAction','teacher',{action:'leaderboard',visible:true});assert.equal(records.get(`${base}/state/leaderboard`).rows.length,2);await invoke('quizAction','teacher',{action:'leaderboard',visible:false});assert.equal(records.get(`${base}/state/leaderboard`).rows.length,0);
 await invoke('quizAction','teacher',{action:'bonus',studentUid:'s1',points:25,actionId:'bonus-1'});await invoke('quizAction','teacher',{action:'bonus',studentUid:'s1',points:25,actionId:'bonus-1'});assert.equal(records.get(`${root}/quizScores/s1`).points,130);
 await invoke('quizAction','teacher',{action:'reveal'});assert.equal(records.get(`${base}/state/quiz`).correct,1);
 await invoke('quizAction','teacher',{action:'next'});q=records.get(`${base}/state/quiz`);now+=100;await invoke('submitQuizAnswer','s1',{roundId:q.roundId,choice:0});now+=200;await invoke('submitQuizAnswer','s1',{roundId:q.roundId,choice:1});assert.equal(records.get(`${base}/quizRounds/${q.roundId}/answers/s1`).responseMs,300);
 await assert.rejects(()=>invoke('setPermission','s1',{studentUid:'s2',permission:'microphone',value:true}),/Only the teacher/);await invoke('setPermission','teacher',{studentUid:'s1',permission:'whiteboard',value:true});
 const stroke={tool:'arrow',color:'#273858',size:4,points:[10,10,50,50]};await invoke('saveBoard','s1',{strokes:[stroke],revision:0});await assert.rejects(()=>invoke('saveBoard','s1',{strokes:[],revision:1}),/only the teacher/);await assert.rejects(()=>invoke('saveBoard','teacher',{strokes:[stroke],revision:0}),/board changed/);
 await assert.rejects(()=>invoke('claimScreen','s1',{}),/permission/);await invoke('setPermission','teacher',{studentUid:'s1',permission:'screenShare',value:true});await invoke('claimScreen','s1',{});assert.equal(records.get(`${base}/state/shareOwner`).uid,'s1');await invoke('setPermission','teacher',{studentUid:'s1',permission:'removed',value:true});await assert.rejects(()=>invoke('submitQuizAnswer','s1',{roundId:q.roundId,choice:2}),/Join the classroom/);
 await assert.rejects(()=>invoke('presentationAction','s2',{patch:{open:false}}),/Only the teacher/);
 console.log('PASS function handlers: ownership, private keys, expiry scheduling, pause/resume, deadlines, idempotent scoring, answer changes, leaderboard visibility, bonuses, permissions, removal and board conflicts.');
})().catch(e=>{console.error(e);process.exit(1);});
